<?php
$storeId = Mage::app()->getStore()->getStoreId();
$ajax_cart		 		= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/ajax_cart', $storeId); 
$image_product_hover 	= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/image_product_hover', $storeId);
$rating_wishlist_compare	 			= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/rating_wishlist_compare', $storeId); 
$quick_view	 			= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/ajax_quickview', $storeId);  
$thumb_width =  Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/standard_image_width', $storeId);
$thumb_height = Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/standard_image_height', $storeId);
$_productCollection=$this->getProductCollection();
$r = $this->getFrontendHash();
$_helper = $this->helper('catalog/output');
?>
<div class="col-md-4 col-sm-6 col-xs-12">
	<h4 class="spb_heading">
		<p><?php echo $this->getWidgetTitle();?></p>
		<div class="heading-icon"></div>
	</h4>
	<div class="mini-list">
	<?php $i=0; foreach ($_productCollection as $_product): ?>
		<div class="row">
			<div class="col-md-6 col-sm-6 col-xs-6">
				<a href="<?php echo $_product->getProductUrl() ?>">
					<img alt="<?php echo $this->htmlEscape($_product->getName()) ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($thumb_width,$thumb_height); ?>">
				</a>
			</div>
			<div class="col-md-6 col-sm-6 col-xs-6">
				<h5>
					<a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>
				</h5>
				<?php echo $this->getPriceHtml($_product, true) ?>
				<div class="rating-product-box">
			        <?php
				        $_reviews = Mage::getModel('review/review')->getResourceCollection();              
				        $_reviews ->addStoreFilter( Mage::app()->getStore()->getId())  
				                  ->addEntityFilter('product', $_product->getId())
				                  ->addStatusFilter( Mage_Review_Model_Review::STATUS_APPROVED )  
				                  ->setDateOrder()  
				                  ->addRateVotes(); 
			    
			            $avg = 0; 
			            $ratings = array(); 
			            if (count($_reviews) > 0){
			            foreach ($_reviews->getItems() as $_review): ?>
			            <?php foreach( $_review->getRatingVotes() as $_vote ): ?>
			                    <?php $ratings[] = $_vote->getPercent();   ?>
			                <?php endforeach; ?>
			            <?php endforeach;   
			            $avg = array_sum($ratings)/count($ratings); 
			            ?> 
			     
					    <div class="rating-box">  
					    	<div class="rating" style="width: <?php echo ceil($avg) ; ?>%;"></div>  
					    </div>					
				    <?php }?>
			    </div>
			    <div class="novaworks-quick-act">	
				
					<?php if($rating_wishlist_compare):?>		
	
						<?php if ($this->helper('wishlist')->isAllow()) : ?>
							<a title="<?php echo $this->__('Wishlist')?>" class="act-wishlist act-add-to-wishlist button-ajax-wishlist-id-<?php echo $_product->getId()?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" data-id="<?php echo $_product->getId()?>"><i class="fa fa-heart-o"></i>
</a> 
						<?php endif; ?> 
	
						
						<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
							<a title="<?php echo $this->__('Compare')?>" class="act-compare act-add-to-compare button-ajax-compare-id-<?php echo $_product->getId()?>" href="<?php echo $_compareUrl ?>" data-id="<?php echo $_product->getId()?>"><i class="fa fa-retweet"></i>
</a> 
						<?php endif; ?>
					<?php endif; ?>
												
				
				</div>
				
				<div class="novaworks-add-to-cart">
					<?php if($_product->isSaleable()): ?>
						<?php if($ajax_cart):?> 	
							<?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ): ?>
								<a class="ajaxcart_colorbox add_to_cart_small button-ajax-cart-id-<?php echo $_product->getId()?>" onclick="ajaxcart('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>');"><?php echo $this->__('Add to cart')?></a> 
							<?php else:?>		
								<a class="ajaxcart_colorbox add_to_cart_small" href="<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>"><?php echo $this->__('Add to cart')?></a> 
							<?php endif; ?> 
							<?php else:?>
								<a class="ajaxcart_colorbox add_to_cart_small" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>');"><?php echo $this->__('Add to cart')?></a> 
						<?php endif; ?>
					<?php endif; //end for saleable product ?>
				</div>
			    
			</div>
		</div>
	
	<?php endforeach; ?>
	</div>			
</div>






