<?php
 $storeId = Mage::app()->getStore()->getStoreId();
 $ajax_cart		 			= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/ajax_cart', $storeId); 
 $image_product_hover 		= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/image_product_hover', $storeId);
 $rating_wishlist_compare	= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/rating_wishlist_compare', $storeId); 
 $quick_view	 			= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/ajax_quickview', $storeId);  
 $thumb_width 				=  Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/standard_image_width', $storeId);
 $thumb_height 				= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/standard_image_height', $storeId);
 $_productCollection=$this->getProductCollection();
 $r = $this->getFrontendHash();
 $_helper = $this->helper('catalog/output');
?>
<div class="slider-items-products nova-widget-style-<?php echo $this->getWidgetStyle()?> novaworks-items-products">
	<h4 class="spb_heading">
		<p><?php echo $this->getWidgetTitle();?></p>
	</h4>
	<div id="novaworks_slider_<?php echo $r;?>" class="product-flexslider hidden-buttons">
		<div class="slider-items slider-width-col<?php echo $this->getShowItems()?>">	
			<?php $i=0; foreach ($_productCollection as $_product): ?>
	            <?php
	                $oType = false;
	                $product = Mage::getModel('catalog/product');
	                $product->load($_product->getId());
	                foreach ($product->getOptions() as $o) {
	                    $optionType = $o->getType();
	                    if ($optionType == 'file') {
	                        $oType = true;
	                    }
	                }
	            ?>		
			<!-- Item -->
	   		<div class="item">
				<div class="item-product-image-box"> 
					<?php include('labels.phtml')  ?> 
		            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
		            	<?php 
		                if($image_product_hover) { ?>
		                <div class="front margin-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($thumb_width,$thumb_height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></div>
		                <?php
			                 $_gallery = Mage::getModel('catalog/product') -> load($_product -> getId()) -> getMediaGalleryImages();
			                 foreach ($_gallery as $_image ):
		                 ?>
		                 <div class="back product-img-additional margin-image">
		                 	<img src="<?php echo $this -> helper('catalog/image') -> init($_product, 'thumbnail', $_image -> getFile()) -> resize($thumb_width, $thumb_height);?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"/>
		                 </div>
		                 <?php
								break;
								endforeach;
						?>
						<?php
							}else{
						?>
							<div class="margin-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($thumb_width,$thumb_height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
						 	</div>
						<?php	
							}
						?>			               
		            </a>
		            <!-- <div class="product-intification-box"><i class="fa fa-circle-o-notch fa-spin"></i></div> -->

		            <div class="quick-view">
			            <?php if($quick_view): ?>
						<a class="act-quickview-button" href="<?php echo $this->getUrl('ajax/index/quickview',array('product_id'=>$_product->getId()));?>" data-id="<?php echo $_product->getId()?>">
							<i class="fa fa-eye"></i><?php echo $this->__('Quickview')?>
						</a>  				
					<?php endif;?>
		            </div>

			        <div class="product-hover-box">
		           					
						<?php if($rating_wishlist_compare):?>		
		
							<?php if ($this->helper('wishlist')->isAllow()) : ?>
								<a title="Wishlist" class="act-wishlist act-add-to-wishlist button-ajax-wishlist-id-<?php echo $_product->getId()?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" data-id="<?php echo $_product->getId()?>"><span class="wishlist"></span></a> 
							<?php endif; ?> 
		
							
							<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
								<a title="<?php echo $this->__('Compare')?>" class="act-compare act-add-to-compare button-ajax-compare-id-<?php echo $_product->getId()?>" href="<?php echo $_compareUrl ?>" data-id="<?php echo $_product->getId()?>"><span class="compare"></span></a> 
							<?php endif; ?>
					<?php endif; ?> 					

		            </div>
			    </div>
		        <h3 class="product-name">
			        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>
			    </h3>
		    	<div class="rating-product">
		            <div class="rating-product-box">
			            <?php
	                    $_reviews = Mage::getModel('review/review')->getResourceCollection();              
	                      $_reviews->addStoreFilter( Mage::app()->getStore()->getId() )  
	                                ->addEntityFilter('product', $_product->getId())
	                              ->addStatusFilter( Mage_Review_Model_Review::STATUS_APPROVED )  
	                              ->setDateOrder()  
	                              ->addRateVotes(); 
                    
                            $avg = 0; 
                            $ratings = array(); 
                            if (count($_reviews) > 0){
                            foreach ($_reviews->getItems() as $_review): ?>
                            <?php foreach( $_review->getRatingVotes() as $_vote ): ?>
                                    <?php $ratings[] = $_vote->getPercent();   ?>
                                <?php endforeach; ?>
                            <?php endforeach;   
                            $avg = array_sum($ratings)/count($ratings); 
                            ?> 
                     
                    <div class="rating-box">  
                      <div class="rating" style="width: <?php echo ceil($avg) ; ?>%;"></div>  
                    </div>					
                    <?php }?>
                    </div>	        	</div>
				<?php echo $this->getPriceHtml($_product, true) ?>
	
				<?php if($this->getShowQuickAct()) { ?>
				<div class="novaworks-quick-act">	
				<?php if($_product->isSaleable()): ?>
					<?php if($ajax_cart):?> 	
						<?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ): ?>
							<a class="ajaxcart_colorbox add_to_cart_small button-ajax-cart-id-<?php echo $_product->getId()?>" onclick="ajaxcart('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>');"><?php echo $this->__('Add to cart')?></a> 
						<?php else:?>		
							<a class="ajaxcart_colorbox add_to_cart_small" href="<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>"><?php echo $this->__('Add to cart')?></a> 
						<?php endif; ?> 
						<?php else:?>
							<a class="ajaxcart_colorbox add_to_cart_small" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Add to cart')?></a> 
						<?php endif; ?>
					<?php endif; //end for saleable product ?>	

				</div>
				<?php }?>
					
		    </div>
		    <!-- End Item -->
	
			<?php endforeach; ?>
		</div>
	</div>
</div>
<script type="text/javascript">
//<![CDATA[
	jQuery(document).ready(function($) {
		jQuery("#novaworks_slider_<?php echo $r;?> .slider-items").owlCarousel({
			items : <?php echo $this->getShowItems()?>, //10 items above 1000px browser width
	    	itemsDesktop : [1024,<?php echo $this->getShowItemsDesktop()?>], //5 items between 1024px and 901px
	      	itemsDesktopSmall : [900,<?php echo $this->getShowItemsDesktopSmall()?>], // 3 items betweem 900px and 601px
	      	itemsTablet: [600,<?php echo $this->getShowItemsTablet()?>], //2 items between 600 and 0;
	      	itemsMobile : [320,<?php echo $this->getShowItemsMobile()?>],
	      	navigation : true,
	      	navigationText : ["<a class=\"flex-prev\"></a>","<a class=\"flex-next\"></a>"],
	      	slideSpeed : 500,
	      	pagination : false
    	});
	}); 
//]]>
</script>






