
<?php
$d_row              = Mage::helper('producttab')->getCf('row');
$slide              = $this->getFirst();
$_productCollection = $this->getCollection();
$_helper            = $this->helper('catalog/output');
$_collectionSize    = $_productCollection->count();
$_id                = $this->getConfig('id');
$title              = $this->getConfig('widget_title');
$identifier			= rand();
$class              = 'products-'.$identifier;
$_column		= '';
/* $productTable=$this->loadTableDataById($slide['arw_tab_id']);
$type_product=Mage::getModel('producttab/product_type')->toOptionArray(); */
$name_type_product  = $this->getNameTypeProduct($slide['arw_tab_id']);
if($slide['arw_use_default']==0){
    $_scroll=$slide['arw_enable_scroll'];
    switch($_scroll){
        case ARW_ProductTab_Model_Content::SHOW_SLIDE:
            $_rowCount              = $slide['arw_row'];
            $loop                   = $slide['arw_animation_loop'];
            $autoplay               = $slide['arw_auto_play'];
            $autoplayTimeout        = $slide['arw_speed'];
            $dots                   = $slide['arw_enable_dots'];
            $navigation             = $slide['arw_enable_navigation'];
            $lazy                   = $slide['arw_lazy_loading'];
            $responsive             = $slide['arw_responsive'];
            $_columnCount           = $slide['arw_limit'];
            $class_products_list    = 'products-slide';
            break;
        case ARW_ProductTab_Model_Content::SHOW_GRID:
            $_column                = $slide['arw_column'];
            $_columnCount           = $_column;
            $class_products_list    = 'products-grid';
            break;
        case ARW_ProductTab_Model_Content::SHOW_FULLGRID:
            $_column                = $slide['arw_column'];
            $_columnCount           = $_column;
            $class_products_list    = 'products-grid';
            break;
        default:
    }
}elseif($slide['arw_use_default']==1){
    $_scroll=Mage::helper('producttab')->getCf('enable_scroll');
    switch($_scroll){
        case ARW_ProductTab_Model_Content::SHOW_SLIDE:
            $_rowCount              = Mage::helper('producttab')->getCf('row');
            $loop                   = Mage::helper('producttab')->getCf('loop');
            $autoplay               = Mage::helper('producttab')->getCf('autoplay');
            $autoplayTimeout        = Mage::helper('producttab')->getCf('speed');
            $dots                   = Mage::helper('producttab')->getCf('dots');
            $navigation             = Mage::helper('producttab')->getCf('navigation');
            $lazy                   = Mage::helper('producttab')->getCf('lazy');
            $responsive             = Mage::helper('producttab')->getCf('responsive');
            $_columnCount           = Mage::helper('producttab')->getCf('limit');
            $class_products_list    = 'products-slide';
            break;
        case ARW_ProductTab_Model_Content::SHOW_GRID:
            $_column                = Mage::helper('producttab')->getCf('column');
            $_columnCount           = $_column;
            $class_products_list    = 'products-grid';
            break;
        case ARW_ProductTab_Model_Content::SHOW_FULLGRID:
            $_column                = Mage::helper('producttab')->getCf('column');
            $_columnCount           = $_column;
            $class_products_list    = 'products-grid';
            break;
        default:
    }
}else{
}
$respon = '';
if($responsive)
{
    $respon             = explode(',',$responsive);
}
$repon_grid             = 'arw-col-'.$_column;


 $storeId = Mage::app()->getStore()->getStoreId();
 $ajax_cart		 			= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/ajax_cart', $storeId); 
 $image_product_hover 		= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/image_product_hover', $storeId);
 $rating_wishlist_compare	= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/rating_wishlist_compare', $storeId); 
 $quick_view	 			= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/ajax_quickview', $storeId);  
 $detail_view	 			= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/act_detailview', $storeId);
 $thumb_width 				=  Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/standard_image_width', $storeId);
 $thumb_height 				= Mage::getStoreConfig('themeoptions_general/prodcuts_list_page/standard_image_height', $storeId);
 
?>
<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else :?>
    <?php if ($_scroll == ARW_ProductTab_Model_Content::SHOW_SLIDE):?>
        <script type="text/javascript">
            jQuery(document).ready(function($){
                var owl = $('#<?php echo $class ?> .slider-items');
                owl.owlCarousel({
                	items : <?php echo $_rowCount?>,
                    <?php if($lazy): ?>
                    lazyLoad:true,
                    <?php endif; ?>
                    <?php if($navigation): ?>
                    navigation:true,
                    <?php endif; ?>
                    navigationText : ["<a class=\"fa fa-angle-left\"></a>","<a class=\"fa fa-angle-right\"></a>"],
                    margin:10,
                    <?php if($autoplay): ?>
                    autoplay:true,
                    autoplayTimeout:<?php echo $autoplayTimeout?>,
                    autoplayHoverPause: true,
                    <?php endif; ?>
                    <?php if($loop): ?>
                    loop:true,
                    <?php endif; ?>
                    <?php if(!$dots): ?>
                    dots:false,
                    <?php endif; ?>
                    pagination : false,
                    responsive:{
                        0 : {
                            items : <?php echo $_rowCount?>
                        }
                       <?php if($respon):?>
                        <?php foreach($respon as $res): ?>
                        <?php $resp=explode(':',$res); ?>
                        , <?php echo $resp[0]?>:{
                    items: <?php echo $resp[1];?>
                        }
                    <?php endforeach; ?>
                    <?php endif;?>
                }
            });
            fixHeightOwlItem(owl);
            });
        </script>
        <div id="<?php echo $class ?>" class="product-flexslider hidden-buttons">
        	<div class="slider-items">	
		        <?php $i=0; foreach ($_productCollection as $_product): ?>
				<?php
		            $oType = false;
		            $product = Mage::getModel('catalog/product');
		            $product->load($_product->getId());
		            foreach ($product->getOptions() as $o) {
		                $optionType = $o->getType();
		                if ($optionType == 'file') {
		                    $oType = true;
		                }
		            }
		        ?>
		    <!-- Item -->
	   		<div class="item">
				<div class="item-product-image-box"> 
					<?php include('labels.phtml')  ?> 
		            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
		            	<?php 
		                if($image_product_hover) { ?>
		                <div class="front margin-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($thumb_width,$thumb_height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></div>
		                <?php
			                 $_gallery = Mage::getModel('catalog/product') -> load($_product -> getId()) -> getMediaGalleryImages();
			                 foreach ($_gallery as $_image ):
		                 ?>
		                 <div class="back product-img-additional margin-image">
		                 	<img src="<?php echo $this -> helper('catalog/image') -> init($_product, 'thumbnail', $_image -> getFile()) -> resize($thumb_width, $thumb_height);?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"/>
		                 </div>
		                 <?php
								break;
								endforeach;
						?>
						<?php
							}else{
						?>
							<div class="margin-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($thumb_width,$thumb_height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
						 	</div>
						<?php	
							}
						?>			               
		            </a>
		            <!-- <div class="product-intification-box"><i class="fa fa-circle-o-notch fa-spin"></i></div> -->

		            <div class="product-hover-box">
		            	<a class="detail_view" href="<?php echo $_product->getProductUrl() ?>"></a>
			            <div class="quick-view">
				            <?php if($quick_view): ?>
							<a class="act-quickview-button" href="<?php echo $this->getUrl('ajax/index/quickview',array('product_id'=>$_product->getId()));?>" data-id="<?php echo $_product->getId()?>">
								<i class="fa fa-search"></i>
							</a>  				
							<?php endif;?>
			            </div>
			            <div class="detail-view">
						<?php if($detail_view): ?>
							<a class="act-imageview-button" href="<?php echo $_product->getProductUrl() ?>">
								<i class="fa fa-chain"></i>
							</a>
						<?php endif;?>
			            </div>
		            </div>
			    </div>
		        <h3 class="product-name">
			        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>
			    </h3>
		    	<div class="rating-product">
		            <div class="rating-product-box">
			            <?php
	                    $_reviews = Mage::getModel('review/review')->getResourceCollection();              
	                      $_reviews->addStoreFilter( Mage::app()->getStore()->getId() )  
	                                ->addEntityFilter('product', $_product->getId())
	                              ->addStatusFilter( Mage_Review_Model_Review::STATUS_APPROVED )  
	                              ->setDateOrder()  
	                              ->addRateVotes(); 
                    
                            $avg = 0; 
                            $ratings = array(); 
                            if (count($_reviews) > 0){
                            foreach ($_reviews->getItems() as $_review): ?>
                            <?php foreach( $_review->getRatingVotes() as $_vote ): ?>
                                    <?php $ratings[] = $_vote->getPercent();   ?>
                                <?php endforeach; ?>
                            <?php endforeach;   
                            $avg = array_sum($ratings)/count($ratings); 
                            ?> 
                     
                    <div class="rating-box">  
                      <div class="rating" style="width: <?php echo ceil($avg) ; ?>%;"></div>  
                    </div>					
                    <?php }?>
                    </div>	        	
                </div>
				<?php echo $this->getPriceHtml($_product, true) ?>
	
				<div class="novaworks-quick-act">	
				
					<?php if($rating_wishlist_compare):?>		
	
						<?php if ($this->helper('wishlist')->isAllow()) : ?>
							<a title="<?php echo $this->__('Wishlist')?>" class="act-wishlist act-add-to-wishlist button-ajax-wishlist-id-<?php echo $_product->getId()?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" data-id="<?php echo $_product->getId()?>"><i class="fa fa-heart-o"></i>
</a> 
						<?php endif; ?> 
	
						
						<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
							<a title="<?php echo $this->__('Compare')?>" class="act-compare act-add-to-compare button-ajax-compare-id-<?php echo $_product->getId()?>" href="<?php echo $_compareUrl ?>" data-id="<?php echo $_product->getId()?>"><i class="fa fa-retweet"></i>
</a> 
						<?php endif; ?>
					<?php endif; ?>
					
					<?php if($_product->isSaleable()): ?>
						<?php if($ajax_cart):?> 	
							<?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ): ?>
								<a class="ajaxcart_simple add_to_cart_small button-ajax-cart-id-<?php echo $_product->getId()?>" data-product-name="<?php echo $this->htmlEscape($_product->getName()) ?>" onclick="ajaxcart('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>');"><i class="fa fa-shopping-cart"></i></a> 
							<?php else:?>		
								<a class="ajaxcart_colorbox add_to_cart_small" href="<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>"><i class="fa fa-shopping-cart"></i></a> 
							<?php endif; ?> 
							<?php else:?>
								<a class="ajaxcart_colorbox add_to_cart_small" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>');"><i class="fa fa-shopping-cart"></i></a> 
						<?php endif; ?>
					<?php endif; //end for saleable product ?>	
									
				
				</div>
					
		    </div>
		    <!-- End Item -->
		        <?php endforeach ?>
		     </div>
    <?php elseif($_scroll == ARW_ProductTab_Model_Content::SHOW_GRID):?>
<?php
		$_productcolumnCount = $_columnCount;
		if($_productcolumnCount == 6) {
			$_col_md = 2;
			$_layout = "list-1col-6";
		}
		elseif($_productcolumnCount == 4) {
			$_col_md = 3;
			$_layout = "list-1col-4";
		}elseif($_productcolumnCount == 3){
			$_col_md = 4;
			$_layout = "list-1col-3";
		}
?>
    <div class="row products-grid  <?php echo $_layout;?>">
    <?php $i=0;foreach ($_productCollection as $_product): ?>
     		<div class="col-lg-<?php echo $_col_md?> col-md-<?php echo $_col_md?> col-sm-4 col-xs-6 item">
				<div class="item-product-image-box"> 
					<?php include('labels.phtml')  ?> 
		            <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
		                <?php if($image_product_hover) { ?>
		                <div class="front">
			                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($thumb_width,$thumb_height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
			            </div>
		                <?php
			                 $_gallery = Mage::getModel('catalog/product') -> load($_product -> getId()) -> getMediaGalleryImages();
			                 foreach ($_gallery as $_image ):
		                 ?>
		                 <div class="product-img-additional back">
		                 	<img src="<?php echo $this -> helper('catalog/image') -> init($_product, 'thumbnail', $_image -> getFile()) -> resize($thumb_width, $thumb_height);?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"/>
		                 </div>
		                 <?php
								break;
								endforeach;
						?>
						<?php
							}else{
						?>
							<div class="margin-image">
								<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($thumb_width,$thumb_height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
						 	</div>
						<?php	
							}
						?>			               
		            </a>
		            <div class="product-hover-box">
		            	<a class="detail_view" href="<?php echo $_product->getProductUrl() ?>"></a>
			            <div class="quick-view">
				            <?php if($quick_view): ?>
							<a class="act-quickview-button" href="<?php echo $this->getUrl('ajax/index/quickview',array('product_id'=>$_product->getId()));?>" data-id="<?php echo $_product->getId()?>">
								<i class="fa fa-search"></i>
							</a>  				
							<?php endif;?>
			            </div>
			            <div class="detail-view">
						<?php if($detail_view): ?>
							<a class="act-imageview-button" href="<?php echo $_product->getProductUrl() ?>">
								<i class="fa fa-chain"></i>
							</a>
						<?php endif;?>
			            </div>
		            </div>
			        			            
				</div>
    	        <h3 class="product-name">
			        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>
			    </h3>
			    <div class="rating-product">
            		<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
            	</div>
				<?php echo $this->getPriceHtml($_product, true) ?>
			  	
				<div class="novaworks-quick-act">	
				
					<?php if($rating_wishlist_compare):?>		
	
						<?php if ($this->helper('wishlist')->isAllow()) : ?>
							<a title="<?php echo $this->__('Wishlist')?>" class="act-wishlist act-add-to-wishlist button-ajax-wishlist-id-<?php echo $_product->getId()?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" data-id="<?php echo $_product->getId()?>"><i class="fa fa-heart-o"></i>
</a> 
						<?php endif; ?> 
	
						
						<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
							<a title="<?php echo $this->__('Compare')?>" class="act-compare act-add-to-compare button-ajax-compare-id-<?php echo $_product->getId()?>" href="<?php echo $_compareUrl ?>" data-id="<?php echo $_product->getId()?>"><i class="fa fa-retweet"></i>
</a> 
						<?php endif; ?>
					<?php endif; ?>
					
					<?php if($_product->isSaleable()): ?>
						<?php if($ajax_cart):?> 	
							<?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ): ?>
								<a class="ajaxcart_simple add_to_cart_small button-ajax-cart-id-<?php echo $_product->getId()?>" data-product-name="<?php echo $this->htmlEscape($_product->getName()) ?>" onclick="ajaxcart('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>');"><i class="fa fa-shopping-cart"></i></a> 
							<?php else:?>		
								<a class="ajaxcart_colorbox add_to_cart_small" href="<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>"><i class="fa fa-shopping-cart"></i></a> 
							<?php endif; ?> 
							<?php else:?>
								<a class="ajaxcart_colorbox add_to_cart_small" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>');"><i class="fa fa-shopping-cart"></i></a> 
						<?php endif; ?>
					<?php endif; //end for saleable product ?>	
									
				
				</div>
			</div>        
    <?php endforeach ?>
    <?php elseif($_scroll == ARW_ProductTab_Model_Content::SHOW_FULLGRID):?>
    <div class="products-grid-full">
<?php
		$_productcolumnCount = $_columnCount;
		if($_productcolumnCount == 6) {
			$_col_md = 2;
			$_layout = "list-1col-6";
		}
		elseif($_productcolumnCount == 4) {
			$_col_md = 3;
			$_layout = "list-1col-4";
		}elseif($_productcolumnCount == 3){
			$_col_md = 4;
			$_layout = "list-1col-3";
		}
?>
    <div class="products-grid  <?php echo $_layout;?>">
    <?php $i=0;foreach ($_productCollection as $_product): ?>
     		<div class="col-lg-<?php echo $_col_md?> col-md-<?php echo $_col_md?> col-sm-4 col-xs-6 item">
				<div class="item-product-image-box"> 
					<?php include('labels.phtml')  ?> 
		            <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
		                <?php if($image_product_hover) { ?>
		                <div class="front">
			                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($thumb_width,$thumb_height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
			            </div>
		                <?php
			                 $_gallery = Mage::getModel('catalog/product') -> load($_product -> getId()) -> getMediaGalleryImages();
			                 foreach ($_gallery as $_image ):
		                 ?>
		                 <div class="product-img-additional back">
		                 	<img src="<?php echo $this -> helper('catalog/image') -> init($_product, 'thumbnail', $_image -> getFile()) -> resize($thumb_width, $thumb_height);?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"/>
		                 </div>
		                 <?php
								break;
								endforeach;
						?>
						<?php
							}else{
						?>
							<div class="margin-image">
								<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($thumb_width,$thumb_height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
						 	</div>
						<?php	
							}
						?>			               
		            </a>
		            <div class="product-hover-box">	
		            	<!-- <a class="detail_view" href="<?php echo $_product->getProductUrl() ?>"></a> -->
		                        	
		            	<h3 class="product-name">
					        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>
					    </h3>
			            <div class="quick-views">
				            <?php if($quick_view): ?>
							<a class="act-quickview-button" href="<?php echo $this->getUrl('ajax/index/quickview',array('product_id'=>$_product->getId()));?>" data-id="<?php echo $_product->getId()?>">
								<i class="fa fa-search"></i>
							</a>  				
							<?php endif;?>
			            </div>
			            <div class="detail-views">
						<?php if($detail_view): ?>
							<a class="act-imageview-button" href="<?php echo $_product->getProductUrl() ?>">
								<i class="fa fa-chain"></i>
							</a>
						<?php endif;?>
			            </div>
			            
			            
					    <div class="rating-product">
		            		<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
		            	</div>
						<?php echo $this->getPriceHtml($_product, true) ?>
					  	
						<div class="novaworks-quick-act">	
						
							<?php if($rating_wishlist_compare):?>		
	
								<?php if ($this->helper('wishlist')->isAllow()) : ?>
									<a title="<?php echo $this->__('Wishlist')?>" class="act-wishlist act-add-to-wishlist button-ajax-wishlist-id-<?php echo $_product->getId()?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" data-id="<?php echo $_product->getId()?>"><i class="fa fa-heart-o"></i>
		</a> 
								<?php endif; ?> 
			
								
								<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
									<a title="<?php echo $this->__('Compare')?>" class="act-compare act-add-to-compare button-ajax-compare-id-<?php echo $_product->getId()?>" href="<?php echo $_compareUrl ?>" data-id="<?php echo $_product->getId()?>"><i class="fa fa-retweet"></i>
		</a> 
								<?php endif; ?>
							<?php endif; ?>
																																						
						</div>
						<div class="novaworks-quick-act novaworks-add-to-cart">	
							
							<?php if($_product->isSaleable()): ?>
								<?php if($ajax_cart):?> 	
									<?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ): ?>
										<a class="ajaxcart_simple add_to_cart_small button-ajax-cart-id-<?php echo $_product->getId()?>" data-product-name="<?php echo $this->htmlEscape($_product->getName()) ?>" onclick="ajaxcart('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>');"><?php echo $this->__('Add to cart')?></a> 
									<?php else:?>		
										<a class="ajaxcart_colorbox add_to_cart_small" href="<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>"><?php echo $this->__('Add to cart')?></a> 
									<?php endif; ?> 
									<?php else:?>
										<a class="ajaxcart_colorbox add_to_cart_small" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>');"><?php echo $this->__('Add to cart')?></a> 
								<?php endif; ?>
							<?php endif; //end for saleable product ?>
																											
						</div>
		            </div>
			        			            
				</div>
    	        
			</div>        
    <?php endforeach ?>
    </div>
    <?php endif;?>
    </div>
<?php endif; ?>
