
<?php
 $storeId = Mage::app()->getStore()->getStoreId();
 $custom_header	=	Mage::getStoreConfig('themeoptions_theming/theme_header/custom_header', $storeId);
?>
<?php $_cartQty = $this->getSummaryCount() ?>
<div class="parent shopping-bag-item">
<?php if($custom_header == '') { ?>
	<a class="cart-contents" href="<?php echo $this->getUrl('checkout/cart') ?>" title="<?php echo $this->__('View contents of your shopping cart') ?>">
		<i class="fa fa-shopping-cart"></i>
		<?php if($_cartQty > 0):?>	
				    <span><?php echo $_cartQty ?></span>	
		<?php endif ?>
	</a>
<?php }elseif($custom_header == 'custom-header-1') { ?>
	<a class="cart-contents cart-borderd custom-header-1" href="<?php echo $this->getUrl('checkout/cart') ?>" title="<?php echo $this->__('View contents of your shopping cart') ?>">
	<?php echo $this->__('Shopping Cart')?>
		<i class="fa fa-shopping-cart"></i>
		<?php if($_cartQty > 0):?>	
				    <span><?php echo $_cartQty ?></span>	
		<?php endif ?>
	</a>	
<?php }elseif($custom_header == 'custom-header-2') { ?>
	<a class="cart-contents cart-borderd custom-header-2" href="<?php echo $this->getUrl('checkout/cart') ?>" title="<?php echo $this->__('View contents of your shopping cart') ?>">
	<?php echo $this->__('Shopping Cart')?>
		<i class="fa fa-shopping-cart"></i>
		<?php if($_cartQty > 0):?>	
				    <span><?php echo $_cartQty ?></span>	
		<?php endif ?>
	</a>	
<?php }elseif($custom_header == 'custom-header-3') { ?>
	<a class="cart-contents cart-borderd custom-header-3" href="<?php echo $this->getUrl('checkout/cart') ?>" title="<?php echo $this->__('View contents of your shopping cart') ?>">
	<?php echo $this->__('YOUR CART')?>
		<i class="fa fa-shopping-cart"></i>
		<?php if($_cartQty > 0):?>	
				    <span><?php echo $_cartQty ?></span>	
		<?php endif ?>
	</a>	
<?php }?>
    <?php $_items = $this->getRecentItems(); ?>
    	<?php if(count($_items)): ?>
		<div class="shopping-bag">
			<?php if($_cartQty==0):?>
			<div class="bag-header"><?php echo $this->__('There are <a href="%s">0 item</a> in your cart', $this->getUrl('checkout/cart')) ?></div>					
			<?php elseif ($_cartQty==1): ?>
			    <div class="bag-header"><?php echo $this->__('There are <a href="%s">1 item</a> in your cart', $this->getUrl('checkout/cart')) ?></div>
			<?php else: ?>
			    <div class="bag-header"><?php echo $this->__('There are <a href="%s">%s items</a> in your cart', $this->getUrl('checkout/cart'), $_cartQty) ?></div>
			<?php endif ?>
			<div class="bag-contents">
			<?php foreach($_items as $_item): ?>
			    <?php echo $this->getItemHtml($_item) ?>
			<?php endforeach; ?>
			</div>          
			<script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>

			<!--
			<div class="mini-cart-total">
				<div class="sub-total">
					<p><?php echo $this->__('Sub-Total') ?>:</p><?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()); ?>
				</div>
			</div>
			-->

			<div class="bag-buttons">								
				<a href="<?php echo $this->getUrl('checkout/cart') ?>" class="sf-roll-button bag-button">
					<span><?php echo $this->__('View Cart') ?></span>
					<span><?php echo $this->__('View Cart') ?></span>
				</a>

				<a href="<?php echo $this->getUrl('checkout/onepage') ?>" class="sf-roll-button checkout-button">
					<span><?php echo $this->__('Check Out') ?></span>
					<span><?php echo $this->__('Check Out') ?></span>
				</a>
			</div>
	    <?php else: ?>
	    	<div class="shopping-bag">
		        <div class="shopping-no-items">
		            <p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
				</div>

	    <?php endif ?>	
	    </div>            
</div>
